name: flutter_sqlite
description: A new Flutter application.
version: 1.1.0+2
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0+1
flutter:
  uses-material-design: true
